In [1]:
import numpy as np
from scipy.stats import qmc

def fill_tensor_with_sobol(tensor_shape, N):
    # 0で埋められたテンソルを作成
    X = np.zeros(tensor_shape)
    total_entries = np.prod(tensor_shape)  # 総エントリ数

    # ソボル列の生成 (次元はテンソルの形状の次元数)
    sobol = qmc.Sobol(d=len(tensor_shape), scramble=True)
    samples = sobol.random(n=N) * np.array(tensor_shape)  # 各座標をテンソルの範囲にスケール

    # サンプルを整数インデックスに変換し、1で埋める
    for sample in samples:
        index = tuple(sample.astype(int))
        X[index] = 1

    return X

# 例
tensor_shape = (4, 4, 4)  # 3次元テンソルの例
N = 10
filled_tensor = fill_tensor_with_sobol(tensor_shape, N)
print(filled_tensor)

[[[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [0. 0. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]]


/Users/keisukeonoue/ws/constrained_BO_v2/bo-env_v2/lib/python3.12/site-packages/scipy/stats/_qmc.py:958: UserWarning: The balance properties of Sobol' points require n to be a power of 2.
  sample = self._random(n, workers=workers)
